spring.datasource.url=jdbc:postgresql://localhost:5432/docprocessor
spring.datasource.username=postgres
spring.datasource.password=Tank

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level traceId=%X{traceId} jobId=%X{jobId} %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
