spring.datasource.url=jdbc:postgresql://localhost:5432/docprocessor
spring.datasource.username=postgres
spring.datasource.password=Tank

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true