input {
  file {
    path => "/usr/share/logstash/logs/docprocessor.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "docprocessor-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}